version: "3"

services:
  db:
    image: mysql:8.0.25
    # PDOでhostを指定するときにこのコンテナ名を使う
    container_name: mysql_con5
    volumes:
      # データが消えてしまわないようにマウントmysqlのフォルダをマウント
      - ./mysql:/var/lib/mysql
    # MySQL8.0でのデフォルトの認証方式が「caching_sha2_password」なので変更する
    # 設定しないと "The server requested authentication method unknown to the client" とエラーになる
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # 設定必須、rootパスワード
      - MYSQL_ROOT_PASSWORD=interken_pass
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=interken
      - MYSQL_PASSWORD=interken_pass
      # この設定はオプション、イメージの起動時に作成されるデータベース名
      - MYSQL_DATABASE=cms
      - TZ=Asia/Tokyo
    #ports:
    #  - "3306:3306"
    # restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_con5
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql_con5
      - PMA_USER=root
      - PMA_PASSWORD=interken_pass
      - UPLOAD_LIMIT=30M
      - TZ=Asia/Tokyo
    links:
      - db
    ports:
      # 運用時は下の行その次の行のコメントを差し替える
      - "8088:80"
      # - "192.168.0.1:8088:80"
    volumes:
      - "./phpmyadmin/sessions:/sessions"
    # restart: always

  
  web:
    image: nginx:latest
    container_name: web_con5
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "443:443"
    volumes:
      - ./webenv/default:/etc/nginx/conf.d
      #- ./webenv/nginx.conf:/etc/nginx/nginx.conf
      - ./home:/var/www/html/home
    depends_on:
      - php
    # restart: always

  php:
    build: ./phpenv
    image: php_con5
    container_name: php_con5
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./phpenv/php.ini:/usr/local/etc/php/php.ini
      - ./home:/var/www/html/home
    restart: always

